# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('birth_date', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
