# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 20:21
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_users_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
