# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20160306_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Edad'),
            preserve_default=False,
        ),
    ]
