# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_users_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
    ]
