# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 06:19
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_auto_20160306_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=geoposition.fields.GeopositionField(default='', max_length=42),
            preserve_default=False,
        ),
    ]
