# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 07:40
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='specialities',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
