# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 08:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import geoposition.fields
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_users_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="N\xfamero telef\xf3nico debe estar en el formato: '+999999999'. Hasta 15 d\xedgitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=geoposition.fields.GeopositionField(max_length=42, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='users',
            name='specialities',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='Especialidades'),
        ),
    ]
