# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_auto_20160307_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'get_latest_by': 'created'},
        ),
    ]
